### ISSUE TITLE
Add ability to add title tags to enable SVG tooltips

### ISSUE THREAD

**Issue by efatsi** [abeidahmed/rails-heroicon#13]
It would be awesome to be able to do something like
```erb
<%= heroicon "bookmark", alt: "Bookmark this widget" %>
```

Anything provided to `:alt` option would end up in a `<title>` tag nested in the SVG element, which browsers turn into tooltips on hover.

**Comment by abeidahmed** [comment]
This would be a nice addon. Would you like to make this as a PR?
