### ISSUE TITLE
Are there any opportunities to increase the performance? Loading 500 icons takes ~45ms but loading the svgs directly takes ~5ms

### ISSUE THREAD

**Issue by nickjj** [abeidahmed/rails-heroicon#34]
I noticed when I don't use this gem my pages respond in 4-5ms in the dev console.

When I output 20 heroicons with this gem it doubles to about 10ms and with 500 heroicons it jumps to 45ms.

If I view the source code of what your gem provided with those 500 heroicons and copy all of the svgs and use them directly in my erb template without calling your gem, the same page renders in ~5-10ms (variance).

Are there any spots to optimize how this gem loads and picks the icon?

I noticed `lib/rails_heroicons.rb` has:

```rb
module RailsHeroicon
  ICON_PATH = File.join(File.dirname(__FILE__), "../compressed/icons.json")
  ICONS = JSON.parse(File.read(ICON_PATH)).freeze
end
```

I patched that to this:

```rb
module RailsHeroicon
  ICON_PATH ||= File.join(File.dirname(__FILE__), "../compressed/icons.json").freeze
  ICONS ||= JSON.parse(File.read(ICON_PATH)).freeze
end
```

But it didn't make a difference. I verified the patch was active because I tried to redefine ICON_PATH and Ruby said I can't since it was previously defined which makes me think the patch was successful. I dropped that into a Rails initializer.

Any suggestions on what we can do to further optimize things?

In my opinion it's worth it because it's very possible to render 50-100 icons on 1 page. Imagine a table where you return 25 rows but each row has 3 icons. That's 75. If you return 50 rows suddenly that's 150 heroicons.

**Comment by nickjj** [comment]
I did a bit of poking and testing.

If you replace `@options.merge!(svg_properties)` with `@options.merge!({})` in `lib/rails_heroicon.rb`'s initializer then it goes from 50ms down to 20ms. Of course that breaks being able to override things but I think that `svg_properties` method is causing the biggest chunk of slowdowns.

**Comment by abeidahmed** [comment]
We can potentially add some cache in this [module](https://github.com/abeidahmed/rails-heroicon/blob/main/lib/rails_heroicon/helper.rb#L4) and conditionally [build](https://github.com/abeidahmed/rails-heroicon/blob/main/lib/rails_heroicon/helper.rb#L37) icons. For example:

```ruby
module Helper
  mattr_accessor :cache, default: {}

  def heroicon(symbol, title: nil, **options)
    cache_key = [symbol, title, options]

    if (tag = cache[cache_key])
      tag
    else
      icon = RailsHeroicon.new(symbol, **options)
      title_tag = content_tag(:title, title) if title
      tag = content_tag(:svg, title_tag.to_s.html_safe + icon.svg_path.html_safe, icon.options)
      cache[cache_key] = tag
      tag
    end
  end
end
```

The above optimization, if it works, might be helpful in this case, "Imagine a table where you return 25 rows but each row has 3 icons. That's 75. If you return 50 rows suddenly that's 150 heroicons" because most of the time the icons are repeated. See the picture below where the "pdf" and the "download" icons are being repeated.

![image](https://user-images.githubusercontent.com/50948617/221402221-b19952a0-39e5-4833-b237-a0750c861542.png)
> Screenshot from: https://dribbble.com/shots/19771250-Plans-and-billing-settings-Untitled-UI

What do you think?

**Comment by nickjj** [comment]
That is true about them repeating in a table, good idea. Your patch did bring responses times down from 45ms to about 15ms.

On that Dribble page you linked I'm counting 14 distinct icons. I think we'd still benefit from addressing `svg_properties` since that amount of icons can nearly double your response time with that amount of icons. Getting low response times in Rails is hard, the difference between 5ms and 10ms might seem little but these things add up.

I'm not really sure how to optimize it yet tho.

**Comment by abeidahmed** [comment]
> Your patch did bring responses times down from 45ms to about 15ms with 500 repeated icons.

Great. I'll play around with the cache a bit and if it looks good, then I'll update this repo.

> I think we'd still benefit from addressing svg_properties since that amount of icons can nearly double your response time

True. Right now, I don't have many ideas about how to optimize the method. Let me think on this and I'll update this issue with a viable solution.

**Comment by tkoenig** [comment]
Hi, I am currently also looking at using heroicons in a rails project and was reviewing different implementations regarding speed.

I also was looking at the `octicons` implementation from Github: https://github.com/primer/octicons/blob/main/lib/octicons_helper/lib/octicons_helper/helper.rb

```ruby
require "octicons"
require "action_view"

module OcticonsHelper
  include ActionView::Helpers::TagHelper

  mattr_accessor :octicons_helper_cache, default: {}

  def octicon(symbol, options = {})
    return "" if symbol.nil?

    cache_key = [symbol, options]

    if tag = octicons_helper_cache[cache_key]
      tag
    else
      icon = Octicons::Octicon.new(symbol, options)

      tag = content_tag(:svg, icon.path.html_safe, icon.options).freeze # rubocop:disable Rails/OutputSafety
      octicons_helper_cache[cache_key] = tag
      tag
    end
  end
end
```

This also seems like an easy way to improve performance?

**Comment by tkoenig** [comment]
Oh, I just noticed you where stating the same example in your code 🫣

**Comment by abeidahmed** [comment]
> Hi, I am currently also looking at using heroicons in a rails project.

Thank you for your consideration. I hope the gem can live up to your expectation.

> This also seems like an easy way to improve performance?

Yes, seems like this can improve performance, especially for the repeating icons. I haven't benchmarked though. Happy to accept a PR :smile: 

As @nickjj said, if we can improve the [`svg_properties`](https://github.com/abeidahmed/rails-heroicon/blob/main/lib/rails_heroicon/rails_heroicon.rb#L29) method, then that would be a big win. I'll look into what I can do to speed up the method in the coming weekend.

**Comment by nickjj** [comment]
Thanks. I'm also sort of thinking about it in the background. When it comes to things like this, sometimes it's easy to get lost in the details. For example, is there a solution that doesn't require ever merging or storing things into a JSON? I don't know the answer, just throwing out ideas to think about when trying to improve performance.

**Comment by juliendecoster** [comment]
@abeidahmed maybe we can close this issue now that the related PR is merged?
