### ISSUE TITLE
Custom stroke is being applied in the HTML for the svg and path, but the path doesn't get updated

### ISSUE THREAD

**Issue by nickjj** [abeidahmed/rails-heroicon#37]
Here's the same icon being rendered with this gem and straight from heroicons if you copy / paste the SVG.

```erb
<%= heroicon "question-mark-circle", size: 16, "stroke-width" => 2 %>
```

It produces this HTML:

```html
<svg stroke-width="2" viewBox="0 0 24 24" height="16" width="16" version="1.1" fill="none" stroke="currentColor" aria-hidden="true">
  <path d="M9.87891 7.51884C11.0505 6.49372 12.95 6.49372 14.1215 7.51884C15.2931 8.54397 15.2931 10.206 14.1215 11.2312C13.9176 11.4096 13.6917 11.5569 13.4513 11.6733C12.7056 12.0341 12.0002 12.6716 12.0002 13.5V14.25M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM12 17.25H12.0075V17.2575H12V17.25Z" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  </path>
</svg>
```

Here's the HTML straight from heroicons' website if you paste the svg:

```html
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
  <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z" />
</svg>
```

And here's a screenshot (left = this gem, right = heroicons website):

![image](https://user-images.githubusercontent.com/813219/224573006-551736d2-1f0b-4946-bb29-57c184416939.png)

This isn't limited to the question-mark-circle icon. This happens with all of the icons I've tried. This gem puts (2) different strokes. One on the svg and one on the path, but the path's stroke is never set. I don't think we need to set it on the path since it's not set on the official heroicons site?

Also the path is much longer with your gem vs what's pasted from the hericons site.

**Comment by abeidahmed** [comment]
> Also the path is much longer with your gem vs what's pasted from the hericons site.

They use [`svgo`](https://github.com/tailwindlabs/heroicons/blob/master/package.json#L30) library to compress the SVG and we don't. This might be the reason why.

**Comment by nickjj** [comment]
> They use [svgo](https://github.com/tailwindlabs/heroicons/blob/master/package.json#L30) library to compress the SVG and we don't. This might be the reason why.

There's an optimized version of the icons in https://github.com/tailwindlabs/heroicons/tree/master/optimized, perhaps in the future this gem could use those instead of the regular non-optimized version?

**Comment by abeidahmed** [comment]
> There's an optimized version of the icons in https://github.com/tailwindlabs/heroicons/tree/master/optimized, perhaps in the future this gem could use those instead of the regular non-optimized version?

Oh right. I'll update the gem and release a version soon.

Thanks!

**Comment by abeidahmed** [comment]
The gem now uses the compressed version of the heroicons https://github.com/abeidahmed/rails-heroicon/pull/42
