### ISSUE TITLE
Ability to customise the defaults

### ISSUE THREAD

**Issue by enstyled** [abeidahmed/rails-heroicon#41]
Thank you for this gem!

Typically one will follow mostly the same options (`variant`, `size`, etc.), across their UI. If the desired style is not what is set as the default (`outline`, 24px), it is required to set the options for every icon and if later you want to change any of the options, you have to go and update every instance.

What do you think about exposing the defaults for customisation, so e.g. one can set the defaults they want and only overwrite when needed?

**Comment by abeidahmed** [comment]
Sounds like a good idea to me. I'm happy to accept a PR on the feature. (Just to make sure we're on the same page, did you mean something like the `devise.rb` config file found in the `config/initializers` directory?)

Apologies for the late reply. I was busy the past 2 weeks due to Ramadan and work.

**Comment by abeidahmed** [comment]
I needed this feature in one of my projects and I solved it by defining a custom helper in the `app/helpers/application_helper.rb` file.

```rb
def icon(name, **options)
  options[:variant] ||= :solid # set "solid" as the default `variant`
  options[:class] = class_names(options.delete(:class), "my-icon-class") # always add the "my-icon-class"
  options[:size] = options[:variant] == :solid ? 20 : options[:size] # default to size 20 for the "solid" `variant`

  heroicon(name, **options)
end
```

Since it's a simple view helper, you can customize it to your needs.
