### ISSUE TITLE
Update to latest icons

### ISSUE THREAD

**Issue by mtomov** [abeidahmed/rails-heroicon#50]
Hello,

Thanks for this library, it's very easy to use, all the options that we need! Thank you!

There's a handful of new icons that are added to the latest version of Heroicons. 

If you describe the steps to update to the latest version in the Readme, I'm happy to propose a PR.

Thank you!

Martin

**Comment by abeidahmed** [comment]
Thank you for your interest in contributing to this project.

I wrote a [contributing guide](https://github.com/abeidahmed/rails-heroicon/blob/main/CONTRIBUTING.md#adding-new-heroicons) a while back and off the top of my head, it seems like it should work. Could you give it a try? Thanks!
